### ISSUE TITLE
http://vpsIPAddr:8000/api/v1/projects 502 (Bad Gateway) app.js:2 FAIL

### ISSUE THREAD

**Issue by em57** [taigaio/taiga-scripts#19]
Hi,
I am getting an error similar to the one that pawel2105 had on issue #5 . I am trying to follow here and apply the fix that niwibe  suggested but there is no taiga-front/app/config/main.coffee file nor taiga-front/app/config/ directory! 
I am using a fresh installation of ubuntu 14.0.4 on a digital ocean VPS on which i just installed Git and everything else is default. i am also using a sudo user called taiga
I simply can not make any APIs calls at all. here is what i get in my browser's console, any help?
```
Initialize navigation urls
jquery.js:10 Initialize api urls
jquery.js:10 Using the default logging exception handler.
jquery.js:10 Initialize resources
jquery.js:10 Initialize application
jquery.js:10 Analytics: no acount id provided. Disabling.
jquery.js:9 GET http://digitaloceanIPAddr:8000/api/v1/projects 502 (Bad Gateway)
app.js:2 FAIL 
```

**Comment by em57** [comment]
As i am still trying to narrow down this issue, service that should run on port 8001 is not running and therefore no API calls will ever happen! any advice on how to get this app up and running ?

**Comment by em57** [comment]
while i didn't get an answer on this issue, I no longer have the above error. I built another VPS and ran the script installation and this time it worked fine. I am wondering why it happened in the first place!

**Comment by superalex** [comment]
It seems that some package installation failed, could you check your install logs from the first machine?

Regards

**Comment by em57** [comment]
At the moment i closed this ticket, I destroyed those older VPSs :(

**Comment by superalex** [comment]
You are welcome! :(

**Comment by 7sedam7** [comment]
I have this error, I have tried to install it multiple times.

**Comment by bameda** [comment]
Hi @7sedam7  try to set the correct API url In settings file at taiga-front-dist/dist/js/conf.json

**Comment by 7sedam7** [comment]
@bameda 

I have this there:

{
       "api": "/api/v1/",
       "eventsUrl": null,
       "debug": "true",
       "publicRegisterEnabled": true,
       "feedbackEnabled": false,
       "privacyPolicyUrl": null,
       "termsOfServiceUrl": null,
       "maxUploadFileSize": null,
      "gitHubClientId": null,
      "contribPlugins": []
}

what should it be there...

**Comment by 7sedam7** [comment]
And during installation I got the following error:

Command /home/taiga/.virtualenvs/taiga/bin/python3.4 -c "import setuptools, tokenize;__file__='/home/taiga/.virtualenvs/taiga/build/lxml/setup.py';exec(compile(getattr(toke      nize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ihzyrhdm-record/install-record.txt --single-version-externally-man      aged --compile --install-headers /home/taiga/.virtualenvs/taiga/include/site/python3.4 failed with error code 1 in /home/taiga/.virtualenvs/taiga/build/lxml
 Exception information: 
Traceback (most recent call last):   File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main     status = self.run(options, args)  
File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/commands/install.py", line 283, in run     requirement_set.install(install_options, global_options, root=options.root_path)   
File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/req.py", line 1435, in install     requirement.install(install_options, global_options, *args, **kwargs)   
File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/req.py", line 706, in install     cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)   
File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/util.py", line 697, in call_subprocess     % (command_desc, proc.returncode, cwd)) pip.exceptions.
InstallationError: Command /home/taiga/.virtualenvs/taiga/bin/python3.4 -c "import setuptools, tokenize;__file__='/home/taiga/.virtualenvs/taiga/build/lxml/s      etup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ihzyrhdm-record/install-record.t      xt --single-version-externally-managed --compile --install-headers /home/taiga/.virtualenvs/taiga/include/site/python3.4 failed with error code 1 in /home/taiga/.virtualenv      s/taiga/build/lxml

**Comment by bameda** [comment]
"api" must be a valid absolute url, try to change to 
```
    "api": "http://localhost:8000/api/v1/",
```
(or something similar)

**Comment by bameda** [comment]
to install lxml you need ```libxml2-dev``` and ```libxslt-dev``` so if you don't have this packages in you system you have to install them with:
```
sudo apt-get install libxml2-dev libxslt-dev
```
and now you can install lxml again
```
pip install --upgrade lxml
```

Sometimes the problem is because your system doesn't have enough RAM.

**Comment by 7sedam7** [comment]
Thank you a lot for help @bameda and sorry for more bothering.

For lxml libs were already installed and pip install fails.

after updating api I got:

**XMLHttpRequest cannot load http://178.62.75.72:8000/api/v1/projects. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://178.62.75.72' is therefore not allowed access. The response had HTTP status code 502.**

http://178.62.75.72/ is the address if you want to check it out.

**Comment by superalex** [comment]
Hello @7sedam7 now it seems that you are having a javascript security problem, 172.62.75.72:8000 and 172.62.75.72 are different domains for your browser and he is complaining about it. If you were using 127.0.0.1:8000 and 127.0.0.1 it works because your browser understand it's a safe environment.

If you want to serve Taiga in a public way you should configure it via nginx as described in the documentation -> http://taigaio.github.io/taiga-doc/dist/setup-production.html#_final_steps

Regards!,

**Comment by 7sedam7** [comment]
I tried with localhost first and now with 127.0.0.1 and without :8000 but it does not work.

But different errors:

OPTIONS http://localhost:8000/api/v1/projects net::ERR_CONNECTION_REFUSED
app.js:2 FAIL
jquery.js:9 
OPTIONS http://localhost:8000/api/v1/projects net::ERR_CONNECTION_REFUSED
jquery.min.js:4 
Uncaught TypeError: Cannot set property 'cssText' of null
VM706:443 
Uncaught ReferenceError: $ is not defined
VM706:211 
Uncaught ReferenceError: $ is not defined
page-prep.js:6 
Uncaught TypeError: Cannot read property 'addEventListener' of null
jquery.min.js:4 
Uncaught TypeError: Cannot set property 'cssText' of null
VM706:211 
Uncaught ReferenceError: $ is not defined
VM747:443 
Uncaught ReferenceError: $ is not defined

**Comment by superalex** [comment]
Did you update your front settings?, it seems that it's not loading correctly your js files.

**Comment by bameda** [comment]
Hi @7sedam7 , I think you're using user stories as epics. We have spoken about this feature in our blog (https://blog.taiga.io/epic-stories.html) and would like to include it in Taiga in the future.

**Comment by 7sedam7** [comment]
@superalex yeah at `taiga-front/dist/js/conf.json`

@bameda I do not know what are you talking about.

**Comment by superalex** [comment]
Hmmmmm, check the source code of the html to see what js files is trying to get and their urls...are those js urls working?

**Comment by bameda** [comment]
@7sedam7 ouch, sorry, that wasn't going here

**Comment by 7sedam7** [comment]
@superalex I have found only this one and it works `http://178.62.75.72/js/app.js?v=1423548479613`

@bameda ah ok :D

**Comment by superalex** [comment]
I've tested accessing your instance in http://178.62.75.72 and it's trying to use the API on localhost:8000, it can't work that way. That will only work if you access http://localhost

**Comment by 7sedam7** [comment]
But you have said to set it up on localhost (127.0.0.1), what should I do so that it works

**Comment by superalex** [comment]
Yes, localhost will work if you access to localhost, if you access to a remote IP but the API checks your localhost it's not possible :)

I suggested serving Taiga via nginx as documented here -> http://taigaio.github.io/taiga-doc/dist/setup-production.html#_final_steps

**Comment by 7sedam7** [comment]
But nginx is setted up like that, I have installed it with the script

**Comment by superalex** [comment]
If you used taiga-scripts the installation it does only works for accessing via localhost, I would recommend you to follow the steps here http://taigaio.github.io/taiga-doc/dist/setup-production.html checking your config files.

**Comment by sivasai519** [comment]
Hello @superalex 

After installation i am going with http://192.168.1.248:8000/api/v1/
 can't connect to that server
could you please help me out.
Thank you

**Comment by sivasai519** [comment]
Hello @superalex 

Can you please let me know, What is the solution for that.
