### ISSUE TITLE
errors during install

### ISSUE THREAD

**Issue by radiofanat** [taigaio/taiga-scripts#20]
E: Unable to locate package libzmq3-dev
[APT-GET] Installing package nodejs...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package nodejs
[APT-GET] Installing package npm...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package npm
./scripts/setup-nodejs.sh: line 6: -2: substring expression < 0
[APT-GET] Installing package python3-pip...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python3-pip
[APT-GET] Installing package python-pip...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python-pip
[APT-GET] Installing package virtualenvwrapper...
Reading package lists...

**Comment by superalex** [comment]
Could you try an apt-get update before?, it sounds like your repos are not working correctly.

Regards,

**Comment by radiofanat** [comment]
I changed repos mirror from ro tu us but errors are the same

**Comment by superalex** [comment]
But what's your output when you execute an apt-get update?

**Comment by radiofanat** [comment]
oleg@taiga:~/taiga-scripts$ sudo apt-get update
Ign http://security.ubuntu.com trusty-security InRelease
Get:1 http://security.ubuntu.com trusty-security Release.gpg [933 B]
Ign http://us.archive.ubuntu.com trusty InRelease
Get:2 http://security.ubuntu.com trusty-security Release [62.0 kB]
Ign http://us.archive.ubuntu.com trusty-updates InRelease
Hit http://us.archive.ubuntu.com trusty Release.gpg
Get:3 http://security.ubuntu.com trusty-security/main amd64 Packages [193 kB]
Hit http://us.archive.ubuntu.com trusty-updates Release.gpg
Hit http://us.archive.ubuntu.com trusty Release
Get:4 http://security.ubuntu.com trusty-security/restricted amd64 Packages [8,875 B]
Hit http://us.archive.ubuntu.com trusty-updates Release
Get:5 http://security.ubuntu.com trusty-security/main i386 Packages [184 kB]
Hit http://us.archive.ubuntu.com trusty/main amd64 Packages
Get:6 http://security.ubuntu.com trusty-security/restricted i386 Packages [8,846 B]
Hit http://us.archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://us.archive.ubuntu.com trusty/main i386 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty/main Translation-en
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://us.archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://us.archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/restricted Translation-en
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US
Fetched 458 kB in 4s (106 kB/s)
Reading package lists... Done
oleg@taiga:~/taiga-scripts$

**Comment by superalex** [comment]
Hmmmmmm, and if you install manually one of those packages?:

apt-get install npm

**Comment by radiofanat** [comment]
oleg@taiga:~/taiga-scripts$ sudo apt-get install npm
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package npm

**Comment by radiofanat** [comment]
oleg@taiga:~/taiga-scripts$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

**Comment by superalex** [comment]
If you can't find npm package in your ubuntu repos it seems they are not working properly. You should try to configure them properly...

**Comment by radiofanat** [comment]
thanks you, I will try to configure.

**Comment by superalex** [comment]
You are welcome!, I don't know exactly why your repos are failing after the ro to us change. A set of working apt repos:

```
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://es.archive.ubuntu.com/ubuntu/ trusty main restricted
deb-src http://es.archive.ubuntu.com/ubuntu/ trusty main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://es.archive.ubuntu.com/ubuntu/ trusty-updates main restricted
deb-src http://es.archive.ubuntu.com/ubuntu/ trusty-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://es.archive.ubuntu.com/ubuntu/ trusty universe
deb-src http://es.archive.ubuntu.com/ubuntu/ trusty universe
deb http://es.archive.ubuntu.com/ubuntu/ trusty-updates universe
deb-src http://es.archive.ubuntu.com/ubuntu/ trusty-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://es.archive.ubuntu.com/ubuntu/ trusty multiverse
deb-src http://es.archive.ubuntu.com/ubuntu/ trusty multiverse
deb http://es.archive.ubuntu.com/ubuntu/ trusty-updates multiverse
deb-src http://es.archive.ubuntu.com/ubuntu/ trusty-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://es.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse
deb-src http://es.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu trusty-security main restricted
deb-src http://security.ubuntu.com/ubuntu trusty-security main restricted
deb http://security.ubuntu.com/ubuntu trusty-security universe
deb-src http://security.ubuntu.com/ubuntu trusty-security universe
deb http://security.ubuntu.com/ubuntu trusty-security multiverse
deb-src http://security.ubuntu.com/ubuntu trusty-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu trusty partner
# deb-src http://archive.canonical.com/ubuntu trusty partner

## Uncomment the following two lines to add software from Ubuntu's
## 'extras' repository.
## This software is not part of Ubuntu, but is offered by third-party
## developers who want to ship their latest software.
# deb http://extras.ubuntu.com/ubuntu trusty main
# deb-src http://extras.ubuntu.com/ubuntu trusty main
```
