### ISSUE TITLE
Rerunning taiga-scripts?

### ISSUE THREAD

**Issue by teamcoltra** [taigaio/taiga-scripts#21]
So in relation to my other issue I raised in taiga-front I found that the problem is the hostname setting that was used during the taiga-scripts process (it's the only thing I can find with the setting "localhost:8000" I have no idea where this file is actually set so I have a two part question:

1) Would I lose everything if I re-ran taiga-scripts with the proper hostname?

2) Where does this hostname get set? I have already tried the config file and added "url" to it and it didn't help. I just want every instance of "localhost:8000" to be changed to "team.example.com"

**Comment by superalex** [comment]
Hello @teamcoltra,

Rerunning taiga scripts will destroy your data but you could make a database backup before executing them and then restore it.

Anyway I've answered you in your other issue I think you still have something to try :)

**Comment by teamcoltra** [comment]
Thanks @superalex I am trying to look at all my options, I thought maybe if this wouldn't destroy the data this would be a nice quick fix.
