### ISSUE TITLE
Clean installation doesn't work (missing templates)

### ISSUE THREAD

**Issue by Semyazz** [taigaio/taiga-scripts#23]
I tried ubuntu 14.04.1 image and I had some issues with locales (because of that Postgresql doesn't start) but after locale fix and when postgresql is up I still cannot make it work entirely. It looks like something is missing in DB initialization, cos I can log in to the Taiga, however there is no admin user, but I don't have any templates. When I try to create a project I see

    taiga.projects.models.DoesNotExist: ProjectTemplate matching query does not exist

Any idea what went wrong?

**Comment by superalex** [comment]
It seems that your intsallation failed in the "Populate the database with initial basic data"  point, could you try to execute:

```
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py loaddata initial_role
python manage.py collectstatic --noinput
```

If you need to generate random data for your instance you can also make a:
```
python manage.py sample_data
```

**Comment by Semyazz** [comment]
I recreate the VM,  fixed lokale first and install postgresql manualny and after that I ran setup script and now everything works fine.

**Comment by superalex** [comment]
Great! :+1:

**Comment by askz** [comment]
Thanks for this.
