### ISSUE TITLE
How can I upgrade taiga-back and taiga-front to new stable version?

### ISSUE THREAD

**Issue by NemoAlex** [taigaio/taiga-scripts#29]
Hello guys,

Thanks for the great work, It works perfectly.

Here is my question: After install, how can I do the upgrade?
Is it just "git pull" in each project folder?

**Comment by superalex** [comment]
Hello @NemoAlex 

We have the documentation about it here -> http://taigaio.github.io/taiga-doc/dist/setup-production.html#faq-add-extra-functionality

Regards!,

**Comment by luanntvn** [comment]
Hello superalex,
I'm planning to upgrade from 1.8 to 1.9 but I can't find out that section. I can reinstall entire the app but are there any db changes to be migrated manually?
Would you please help?

Thanks,
Luan Nguyen

**Comment by superalex** [comment]
Hello @luanntvn we moved that page, it's actually located here -> http://taigaio.github.io/taiga-doc/dist/setup-faqs.html#faq-maintain-update

Regards!,

**Comment by luanntvn** [comment]
Just found it. Thank you!

**Comment by superalex** [comment]
You are welcome! ;)
