### ISSUE TITLE
docker support

### ISSUE THREAD

**Issue by canercandan** [taigaio/taiga-scripts#3]
Anybody interested porting Taiga to a docker image ?

**Comment by FlorianBezagu** [comment]
:+1: 
Would be great to have an docker image with every part of taiga :
  - taiga-back
  - taiga-front-dist
  - taiga-events

**Comment by ianmiell** [comment]
Do you mean a single image or three?

**Comment by FlorianBezagu** [comment]
Hi @ianmiell 

Yes I mean a single image with the three parts inside it.

We already have an instance of taiga installed but we're moving our servers and I'd like to install taiga on my new Docker server.

**Comment by ianmiell** [comment]
I haven't looked at taiga for a while, but I could help you script an image
with this:

https://registry.hub.docker.com/u/imiell/taigaio/

Built from:

https://github.com/ianmiell/shutit/blob/master/library/taigaio/taigaio.py

But I'm not sure how much of this you know already, or how much taiga has
moved on.

**Comment by benhutchins** [comment]
@FlorianBezagu Check out https://github.com/benhutchins/docker-taiga which is Taiga's front and backend in one, and has support for taiga-events.
