### ISSUE TITLE
Make a Dockerfile

### ISSUE THREAD

**Issue by ayr-ton** [taigaio/taiga-scripts#31]
Implement a Dockerfile and a compose with a container for backend and other one for frontend.

**Comment by ayr-ton** [comment]
I could make a pull request if you guys like this feature.

**Comment by superalex** [comment]
Hello @ayr-ton ,

Thank you very much but actually there are two existing different docker scripts supported by the community:
- https://github.com/ipedrazas
- https://github.com/htdvisser/taiga-docker

Regards!,

**Comment by superalex** [comment]
Two more projects: 
- https://github.com/nsdont/taiga-docker
- https://github.com/nesv/taiga-docker

**Comment by ayr-ton** [comment]
Thank you!

**Comment by superalex** [comment]
You are welcome ;)
