### ISSUE TITLE
How to uninstall taiga?

### ISSUE THREAD

**Issue by renatoramiro** [taigaio/taiga-scripts#33]
I installed taiga by taiga-scripts, but I'm having some problems with backend.

http://<my ip>/api/v1/projects Failed to load resource: net::ERR_CONNECTION_REFUSED

And I want to completely uninstall taiga. How do I uninstall taiga?

**Comment by superalex** [comment]
Hello @renatoramiro,

Actually there is not automated way for uninstalling Taiga, you should remove all the data folders created by taiga (taiga-back and taiga-front), you could also remove the taiga database and then uninstall all the packages you are not needing more...

About the error, what kind of  installation did you do?, server or devel?, did it fail at any point?.

Regards,
