### ISSUE TITLE
HTTP 502 Bad Gateway when trying to login in via admin for the first time

### ISSUE THREAD

**Issue by mehrad-rafigh** [taigaio/taiga-scripts#34]
Hey guys,

I tried to install taiga on a vm, which fulfills the requirements of taiga. Everything is actually working, but when I try to log in for the first time as admin with 123123 as the password, I'll get the Bad Gateway Error. Did somebody experience the same thing and has an idea how to solve this? Any help is highly appreciated!

**Comment by bameda** [comment]
Hi @mehrad-rafigh 

Can you show me your config.json file? Your taiga-front client can connect with your taiga-back server instance.

**Comment by mehrad-rafigh** [comment]
@bameda I already fixed it. It seemed that the error was inside the nginx taiga file. I manually added the admin part and now it works.

**Comment by bameda** [comment]
Great! \o/

**Comment by sivasai519** [comment]
Hello @bameda 

While i was going with this url http://localhost/api/v1 i am getting error in webpage 
502 bad gateway 
can you please help me
