### ISSUE TITLE
Production installation on DigitalOcean

### ISSUE THREAD

**Issue by matt-oakes** [taigaio/taiga-scripts#4]
I've run the production install script on a standard DigitalOcean droplet, where the default user is `root` (Yes I know this is a bad idea, but it was a quick and dirty install to see if I could get it working).

The script finished without error, but it wrote the nginx sites file incorrectly. Instead of the correct home directory for the root user (`/root`) it used `/home/root`.

It's not a big issue because I don't think anyone would really be running this script as root if they were going to use the server properly, but it might be worth fixing for people like me who just wanted something up quickly to test it out.

**Comment by 7sedam7** [comment]
I have installed it with sudo privledges and new user smoothly and when navigated to IP app seemed to be there accept when I tried to create an account I get "Failed to load resource: the server responded with a status of 502 (Bad Gateway)" upon clicking "Sign Up" button.
