### ISSUE TITLE
Default username and password do not work; registration does not work.

### ISSUE THREAD

**Issue by jahwurbw** [taigaio/taiga-scripts#40]
I am using a fresh Ubuntu 14.04 image in AWS. I clone taiga-scripts using a "taiga" user account and execute setup-server.sh successfully. I can access the website, but when attempting to login using admin/123123, I receive the following error:
Oops, something happened...
According to our Oompa Loompas, your username/email or password are incorrect.

Registration also fails with the following error:
"Something happened and our Oompa Loompas are working on it."

I reached the same results when following the manual installation process for a production environment.

**Comment by superalex** [comment]
Hello @jahwurbw 

Did you check the output of setup-server.sh to check if something failed?, you could rebuild your database and initial data with something like:

```
workon taiga
./regenerate.sh
```

Regards,

**Comment by spaceheadx** [comment]
Hi @superalex 

i can confirm this issue (I also tried both, script and manual install).

sadly 
```
workon taiga
./regenerate.sh
```
did not work. The output of the script and regenerate.sh looks good so far.

Best regards,

**Comment by superalex** [comment]
You could check two different things:
 - Your javascript console to see if there is a problem calling the API
 - Your backend logs (from ~/logs folder)

**Comment by spaceheadx** [comment]
Thanks @superalex the javascript console pointed me to the cause of the issue.

editing 
```
"api": "http://myvm.mydomain.com:8000/api/v1/",
```
in *taiga-front/dist/v-1451995127167/js/app-loader.js* did the trick for me.

**Comment by superalex** [comment]
Great!, but it's not recommended you edit that file (updating your instance will remove that changes), customize your dist/conf.json file

**Comment by jahwurbw** [comment]
I ran the script, but am receiving the following error in the Javascript console:
OPTIONS http://localhost:8000/api/v1/auth net::ERR_CONNECTION_REFUSED

What do I need to change?

**Comment by superalex** [comment]
@jahwurbw I've answered you again in the other issue.

Regards!,
