### ISSUE TITLE
OPTIONS http://localhost:8000/api/v1/auth net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by jahwurbw** [taigaio/taiga-scripts#41]
My previous issue was closed prematurely here: https://github.com/taigaio/taiga-scripts/issues/40

I am using a fresh Ubuntu 14.04 image in AWS. I clone taiga-scripts using a "taiga" user account and execute setup-server.sh successfully. I can access the website, but when attempting to login using admin/123123, I receive the following error:
Oops, something happened...
According to our Oompa Loompas, your username/email or password are incorrect.

Registration also fails with the following error:
"Something happened and our Oompa Loompas are working on it."

I reached the same results when following the manual installation process for a production environment.

I am receiving the following error in the Javascript console:
OPTIONS http://localhost:8000/api/v1/auth net::ERR_CONNECTION_REFUSED

I attempted to change "localhost" to the server's IP address via local.py, and I ran regenerate.sh; neither helped to resolve the error.

I verified port :8000 is listening.

**Comment by superalex** [comment]
Hello @jahwurbw,

What url are you using to access your taiga instance?, it sounds like your taiga-front copy isn't configured properly to find the API url, probably you should check your dist/conf.json file.

Regards,

Are you sure you are using the same U

**Comment by jahwurbw** [comment]
Alex,

Thanks for the quick response and staying on top of all of this.

My conf.json file is configured with the following:
{
    "api": "http://[IP ADDRESS]:8000/api/v1/",
    "eventsUrl": null,
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": []
}


Where [IP ADDRESS] is my server's IP.

**Comment by jahwurbw** [comment]
Ok, it looks like the issue was fixed. I had fixed conf.json the other day to reflect my IP address, restarted nginx and circus, and it seems like the new values still did not apply.

I restarted the system today, and the new settings applied.

Thanks Alex for your quick responses.

**Comment by superalex** [comment]
Great!, you are welcome @jahwurbw :)

**Comment by patilkomal** [comment]
Getting this below error please help me to resolve it out:

polyfills.js:3 POST http://localhost/PHP-Slim-Restful/api/signupLogin net::ERR_CONNECTION_REFUSED
s @ polyfills.js:3
t.scheduleTask @ polyfills.js:3
onScheduleTask @ polyfills.js:3
t.scheduleTask @ polyfills.js:3
r.scheduleTask @ polyfills.js:3
r.scheduleMacroTask @ polyfills.js:3
(anonymous) @ polyfills.js:3
o.(anonymous function) @ polyfills.js:2
(anonymous) @ http.js:1605
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
(anonymous) @ auth-service.ts:20
t @ polyfills.js:3
webpackJsonp.50.AuthService.postData @ auth-service.ts:16
webpackJsonp.100.Login.Login @ login.ts:22
(anonymous) @ Login.html:16
handleEvent @ core.js:13255
callWithDebugContext @ core.js:14740
debugHandleEvent @ core.js:14327
dispatchEvent @ core.js:9704
(anonymous) @ core.js:10318
(anonymous) @ platform-browser.js:2614
t.invokeTask @ polyfills.js:3
onInvokeTask @ core.js:4620
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
e.invokeTask @ polyfills.js:3
p @ polyfills.js:2
v @ polyfills.js:2

**Comment by Akachi229** [comment]
I have a problem connecting to my dialoguflow API in my ionic application.
OPTIONS http://localhost:5000/message net::ERR_CONNECTION_REFUSED

**Comment by Luzmario1708** [comment]
Akachi229 
Hi, could you solve it? I have the same problem.
