### ISSUE TITLE
unable to connect with admin/123123 after a fresh install : CORS error involved

### ISSUE THREAD

**Issue by LaurentCabaret** [taigaio/taiga-scripts#42]
After a fresh install with taiga-scripts (production or devel) on a virtualbox clean ubuntu 14.04 machine,
the login page is followed by an error page. 
The firefox console gave me : 
Blocking of a multi- query origins (Cross - Origin Request) : the " Same Origin " policy does not refer to the remote resource on http: // localhost: 8000 / api / v1 / auth . Reason: the header CORS "Access -Control- Allow- Origin " is missing .

I check the local connexion on the machine (with a direct api request) the user admin/123123 is  existing.
  circusctl status 
gave me 
  circusd-stats: active
  taiga: active

I precise that I already do this 6 month before (taiga 1.8) and everything was fine

**Comment by superalex** [comment]
Probably your instance isn't finding correctly your conf.json file, could you try the steps documented here (http://taigaio.github.io/taiga-doc/dist/upgrades.html) to upgrade from 1.9.0 to 1.9.1?

Regards!,

**Comment by LaurentCabaret** [comment]
Tanks for your answer

The 1.8 installation was on an other machine 6 month before (I precire tat point to explain it is a new problem)

The problem is with an install done this morning on a new machine so its already an 1.9.1 version.

Regards too!

**Comment by superalex** [comment]
Could you please show us your conf.json file and what url are you using to access Taiga?

**Comment by LaurentCabaret** [comment]
I checked the conf.json clue : indeed  taiga-front/dist/conf.json was not existing but creating it (with the exemple) had not effect

**Comment by LaurentCabaret** [comment]
Sure : 
conf.json 
{
    "api": "http://localhost:8000/api/v1/",
    "eventsUrl": null,
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": []
}

The virtual machine is accessed with 192.168.56.103 or 192.168.56.103:8000 (I tried both)

**Comment by superalex** [comment]
Probably you should update that conf.json file with a valid API url, what url are you using to access?

**Comment by LaurentCabaret** [comment]
Many thanks!

Indeed changing the line 
"api": "http://localhost:8000/api/v1/",
to 
"api": "http://192.168.56.103:8000/api/v1/",

solved the problem.

To sum up: 
- The taiga-script does not create taiga-front/dist/conf.json
- Once created (cp taiga-front/dist/conf.example.json taiga-front/dist/conf.json) if the server is accessed externaly (not localhost) the api line should reflect the real url access.

Thanks again for your great product and ave a nice day

**Comment by superalex** [comment]
You are welcome!,

We should make that part of the docs more clear :)

Regards,
