### ISSUE TITLE
Getting error while running script

### ISSUE THREAD

**Issue by abhijitroy07** [taigaio/taiga-scripts#43]
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package postgresql-server-dev-9.3
E: Couldn't find any package by regex 'postgresql-server-dev-9.3'
touch: cannot touch ‘/home/bitnami/.setup/postgresql’: No such file or directory
touch: cannot touch ‘/home/bitnami/.setup/buildessential’: No such file or directory
~ ~/taiga-scripts

**Comment by bameda** [comment]
You need http://packages.ubuntu.com/trusty/postgresql-server-dev-9.3
