### ISSUE TITLE
User Creation Problem

### ISSUE THREAD

**Issue by tuffacton** [taigaio/taiga-scripts#49]
After installing using the scripts the landing page loads fine from the VM IP but I can't register new users and therefore can't login to test the rest of the app. Am I missing anything?

**Comment by superalex** [comment]
Hello @tuffacton,

Could you please check your browser console to see if there are any errors?

Regards,

**Comment by tuffacton** [comment]
Hey, there is a consistent 502 which would indicate network problems. I think I figured it out so I'm going to close this one.

**Comment by superalex** [comment]
Ok!
