### ISSUE TITLE
Taiga Docker

### ISSUE THREAD

**Issue by douglasmiranda** [taigaio/taiga-scripts#55]
So, I have my configuration of Taiga running on Docker containers, and I want to share.

https://github.com/douglasmiranda/docker-taiga

I know this is not the best place, but you can close the issue, and it will be here so people can search and find.

Related: #54

**Comment by bameda** [comment]
Hi @douglasmiranda we have a cimminoty section in our suppor pages here

https://tree.taiga.io/support/misc/community-contributions/

Maybe you can sent us a PR

https://github.com/taigaio/taiga-support/blob/master/content/misc/community-contributions/contents.lr
