### ISSUE TITLE
OPTIONS http://localhost:3800/ net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Luzmario1708** [taigaio/taiga-scripts#66]
I am developing a project where my backend is done in node.js and my interface in ionic.

I am managing a mongoDB database, when I run the project from the web and log in, it takes the data correctly, but when I try to run the project from a mobile device I have the following problem.

    OPTIONS http: // localhost: 3800 / net :: ERR_CONNECTION_REFUSED

    ERROR 
    HttpErrorResponse {headers: HttpHeaders, status: 0, statusText: "Unknown Error", url: "http://localhost:3800/api/login", ok: false, …}
    error: ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: "error", …}
    headers: HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, headers: Map(0)}
    message: "Http failure response for http://localhost:3800/api/login: 0 Unknown Error"
    name: "HttpErrorResponse"
    ok: false
    status: 0
    statusText: "Unknown Error"
    url: "http://localhost:3800/api/login"
    __proto__: HttpResponseBase

I did my backend in Node.js and use mongoDb as a database, this is the code used.

    import mongoose from 'mongoose';
    import express from 'express';
    import http from 'http';
    import app from '../rutas/app';
    
    export default class Server {
        port: number = Number( process.env.PORT ) || 3800;
        servicio = require ('http').createServer(app);
    
        connect(){
    
            mongoose.Promise = global.Promise;
            mongoose.connect('mongodb://localhost:27017/DB_mongoDB', { useNewUrlParser: true, useCreateIndex: true })
            .then(() => {
                this.servicio.listen(this.port);
                });
            })
            .catch(err => console.log(err));
        }
    }

Try changing the localhost for my iP but the same error comes up.

The information on my iP is placed in my frontend in my environment folder as follows.

After

    export const environment = {
      production: true,
      url: 'http://localhost:3800'
    };

Before:

    export const environment = {
      production: true,
      url: 'http://181.12.32.422:3800'
      
    };

But it does not work.

I appreciate the help you can give me.

**Comment by migonzalvar** [comment]
Sorry @Luzmario1708 but it seems to me that your issue is totally unrelated with this project.
